name: "Publish to cadet.github.io on push"
on:
  # Trigger the workflow on push
  push:
    branches:
      - main
      - master

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH client
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}
    - name: "Checkout CADET"
      uses: actions/checkout@v2
      with:
        repository: modsim/CADET
        fetch-depth: 0
        persist-credentials: false
    - name: "Checkout CADET-Match"
      uses: actions/checkout@v2
      with:
        repository: modsim/CADET-Match
        fetch-depth: 0
        persist-credentials: false
    - name: "Sphinx build CADET"
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "CADET/doc/"
        pre-build-command: "pip3 install requirements.txt"
        build-command: "sphinx-multiversion . ../../build"
    - name: "Sphinx build CADET-Match"
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "CADET-Match/doc/"
        pre-build-command: "pip3 install requirements.txt"
        build-command: "sphinx-multiversion . ../../build/CADET-Match"
    - name: Deploy to cadet.github.io
      uses: JamesIves/github-pages-deploy-action@3.6.2
      with:
        SSH: true
        BRANCH: master
        FOLDER: build
        CLEAN: true
        REPOSITORY_NAME: cadet/cadet.github.io
        GIT_CONFIG_NAME: "GitHub Deploy Action"
        GIT_CONFIG_EMAIL: "action@github.com"
